azurestandard/api-spec

public.json
We want to display these times when showing user's the current status
of their order.  For orders we deliver to drops, we can find the
delivery time by looking at the stop.time for the associated stop.
But for orders delivered by UPS or another carrier, we'll want to
cache delivery times that we get from the carrier here.
The backend has implemented order.placed since
azurestandard/beehive@37489b5 (apps/api/views/order.py: Set
order.shipped to the shipping date, 2015-03-20).  We store the placed
time already (as Order.order_time, see
azurestandard/beehive@8ae576fcc5, apps/orders/models.py: Add help_text
to Order.order_date, 2015-08-05).  We don't store the delivery time
yet, but I think we should.
=> public.json: Add order.placed, .shipped, and .delivered times

public.json
We collect several person-related attributes when registering new
people (usually customers).  Instead of duplicating schema between
parameters in POST /registration/register and the coming PUT
/person/{id}, collect that new/updated-person schema in a definition
and use *that* in the pushed body.
For silly examples of this approach, see the current updateDrop and
updateRoute. For a bit more meat, see the spec around newPaymentMethod
and paymentMethod. For previous comments about why I'm cheating for
updateDrop and updateRoute, see 03e139a, 168a97b, 1616442, and
27ba2a1. In the route and drop cases, I've slightly broke the spec (by
including nominally requiring 'id').
Related to #7, azurestandard/azure-angular-providers#2,
azurestandard/beehive#1089, and azurestandard/beehive#1025.
=> public.json: Add updatePerson

public.json
This allows users to change their names, email addresses, and passwords.
Fixes #5.
=> Add support for POSTing to /person and /person/{id}.

public.json
We're not currently video-calling people, faxing people,
distinguishing between their home and cell numbers, etc.
=> public.json: Restrict telephoneType to values we can use

public.json
Folks using updatePerson in other contexts are free to only set the
fields they intend to update, but for creating new people we need an
email address (to send the confirmation email) and might as well have
a name ;).
=> public.json: Require name and email for registrants

public.json
Allow users to make payments directly (e.g. to settle outstanding
balances).  Good logging here is important, so I'm using query
parameters to get these into the Nginx logs.
=> public.json: Add POST /account-entries

public.json
This allows us to support the registrant copy/pasting confirmation
URLs into their browser (it's harder to get your browser to POST
without an HTML form or such).
=> public.json: Add 'GET /registration/confirm?token=...'

public.json
We need a consistent way to select a user's primary address, and the
cleanest API for that seems to be letting the user order all their
preferences.  Then setting a new primary address would look something
like (using [azure-angular-providers][1]):
newPrimary.preference = 100;
oldPrimary.preference = 0;
newPrimary.$save().$promise.then(function () {
oldPrimary.$save();
});
There's a low probability that the `newPrimary.$save` goes through and
the `oldPrimary.$save` does not.  If the `oldPrimary.preference` was
originally 100, that means there is some time (while the
`oldPrimary.$save` is in flight, and possibly after if that call fails)
where both addresses will have the same preference on the server.  If
that's a concern, you could use something like:
newPrimary.preference = …
=> public.json: Add address.preference

public.json
A user who is authorized to view all tags may not want to view
internal tags (e.g. they're hitting this endpoint while shopping for
themselves).  This option allows UI code to explicitly set
`?public=true` when they don't intend to access those internal tags.
I expect most UIs will be setting `?public=true`, but defaulting to
limited results (and requiring folks to specify `?all=true` or some
such) would break our usual pattern of “show everything and filter
with query parameters”.
=> public.json: Add public=? boolean to /packaged-product-tags

public.json
This slipped through with cf10fceb (public.json: Add
address.preference, 2015-08-31, #17).
=> public.json: Remove a trialing comma from address.preference.format

public.json
The `registerPerson` endpoint uses the `registration` model, which
includes the `updatePerson` model.  To avoid folks having to guess
what happens when they don't specify a boolean field, this commit
explicitly lists the default value for those fields.
If a field is not specified during an `updatePerson` call, we leave it
alone.
=> public.json: List the default values for boolean person creation

public.json
On Tue, Sep 15, 2015 at 12:19:21PM -0700, heuscher [wrote][1]:
> Reference Google spec document 8.7.1 Current Drop.
>
> Need to return the minimum, total order amount
> (`drop.minimum_order_amount`) required for a drop.
Part of azurestandard/beehive#1192.
[1]: https://github.com/azurestandard/beehive/issues/1192
=> public.json: Add drop.order-minimum

public.json
This snuck in with 6a2d0e629 (public.json: Add /products and
/product/{code}, 2014-11-26).
=> public.json: Add a trailing paren to price.discount.description

public.json
This snuck in with 6a37b83c (public.json: Add drop.order-minimum,
2015-09-15, #26).  I need CI to validate my JSON ;).
=> public.json: Remove an extra closing brace from order-minimum

public.json
This is a first step in our shift to more flexible pricing.  The
current API implementation checks the requester's price level and
returns the appropriate prices object (now _price, after this
commit). As we shift to Algolia for product searches, we'll need less
dynamic pricing information, because Algolia isn't going to
authenticate reqeusters for us.  This commit associates
requester-independent pricing information with the packaged-products,
and gives customers the information they need (via their /person or
/person/{id} result) to select the appropriate price from the satic
packaged-products information.
In the future, we will likely transition to a more
complicated/flexible pricing model, with base-price information on
packaged-products that's not price-level dependent (e.g. a base …
=> public.json: Add person.price-level and a multi-level price object

public.json
Customers expect access to this:
On Thu, Sep 17, 2015 at 02:59:57PM -0700, Jordan Schatz wrote [1]:
> > By "is currently displayed" do you mean old site, new site, or
> > both?
>
> Old site, invoices, emails, etc. The customers are accustomed to
> being able to see it.
This commit just copies our current handling of orderLine.weight.  The
cubic-foot measurement matches the existing internal calculations, and
the US still hasn't seen the metrification light ;).
See azurestandard/website#66 and azurestandard/beehive#1197.
[1]: https://github.com/azurestandard/website/issues/66#issuecomment-141243331
=> public.json: Add orderLine.volume

public.json
The existing Beehive API actually had a 'POST /account-entries'
implementation, but it was just for creating account entry instances,
and not for side effects like settling credit card charges.  We want
to keep those entry-creation instances so we can do things like credit
customers for damaged orders (there's no payment-method then), so
shift the new-payment endpoint from 2b8dbfe (public.json: Add POST
/account-entries, 2015-08-28, #16) over to 'POST /payments'.
=> public.json: Move 'POST /account-entries' to 'POST /payments'

public.json
The current 'person' landed in 272387d5 (Add methods to manage a
person's filter preferences, 2015-08-14, #13), after [I suggested it
during review][1]:
13:31 <+wking> cbessette: orders are like person-tags in their
relationship with people.  Maybe just:
/packaged-product-tag-associations, where we push/delete {'person':
<id>, 'tag': <slug>} objects?  And then
/packaged-product-tag-associations?person=<your-id> to get your
personal tags?
13:31 <+cbessette> That sounds good to me, I'll update it.
However, I'd forgotten that 2ab80437 (public.json: Add
packagedProduct.favorite boolean and annotate-person parameter,
2015-06-08) had changed the 'person' query parameter to
'filter-person' (to avoid confusion with annotate-person).  This
commit adjusts the name to catch up, and copies the …
=> public.json: 'person' -> 'filter-person' for GET /packaged-product-tag-associations

public.json
Since 01861207 (public.json: Add person.price-level and a multi-level
price object, 2015-09-16, #29) the price structure is more involved,
and API implementations would have to build enough of the price
structure to put a price on post-price-freeze lines.  I think that is
the wrong approach, because as the price model becomes more dynamic,
the chance of one of the external variables changing increases.  For
example, it's not impossible (but maybe not very likely) that a
customer changes from retail to wholesale, but once we start including
per-route information, etc. in the pricing calculation, it becomes
harder to figure out what values we should be faking in the
reconstituted price object.  And it seems like wasted, brittle work to
go from a dollar price to a complicated price structure …
=> public.json: Make orderLine.price a total dollar value

public.json
Fix a copy-paste error from 168a97b4 (public.json: Add '{GET|POST}
/payment-methods' and 'GET /payment-method/{id}' endpoints,
2015-02-11).
=> public.json: Drop second newCreditCard.description

public.json
So customers can associate a payment method (e.g. a credit card) to be used
for paying off the order (by PUTing or POSTing orders with
checkout-payment.payment-method set).  After shipping, checkout-payment
will just become a record of whether or not they associated a payment
method with the order (e.g. they may have not associated a payment method,
and just covered the order with previous credits from POST /payments or
some such).
This adds a specification for the implemetation that landed in
azurestandard/beehive@34e7a19c (apps/api/views/order.py: Add
order.payment fields, 2015-04-23).  The first commit just sets the
stage, but will require minor edits to API consumers.
=> public.json: Add order.checkout-payment

public.json
I landed the previous syntax in 168a97b4 (public.json: Add '{GET|POST}
/payment-methods' and 'GET /payment-method/{id} ' endpoints,
2015-02-11), which pointed out that anyOf isn't valid Swagger 2.0.
But it's looking like the consensus is around including it in the next
Swagger release [1].  The JSON Schema example I was following [2]
didn't use $ref in their example, but they do use $ref in their allOf
example [3].  This commit updates the existing anyOf uses to match
that syntax.
[1]: https://github.com/swagger-api/swagger-spec/issues/57#issuecomment-56224153
[2]: http://spacetelescope.github.io/understanding-json-schema/reference/combining.html#anyof
[3]: http://spacetelescope.github.io/understanding-json-schema/reference/combining.html#allof
=> public.json: Adjust anyOf syntax to use schema and $ref

public.json
According to a Hangout with Tom, we no longer need to support this
concept.
=> Remove accept-cash-on-delivery from drop definition.

public.json
Based on `stop.target-time` and `stop.estimated-time`, which is where
this information will come from after the trip is verified (which is
when the stops are created).  Before that, both fields will be:
trip.delivery-start + route-stop.delivery-offset
using the order's trip and the route-stop associated with the order's
`trip.route` and `drop`.  UPS orders have neither a trip or drop, and
customers are encouraged to use their UPS tracking number to retrieve
this sort of information directly from UPS.
This information is currently available via the stop, route-stop, and
trip endpoints, but logic to handle:
1. Are we post-verification (or post-shipping, or something in that
timeframe)?
* Yes: lookup the stop.
* No: lookup the trip and route-stop.
will have to live somewhere.  We don't know …
=> public.json: Add order.target-delivery and .estimated-delivery

public.json
This will be used by the frontend to filter unwanted tags from being
displayed.   This way product status tags, e.g., can be distinguished
from other tag types.
=> Add category property to packagedProductTag definition.

public.json
Builds on #39, so review/merge that first.
Existing fees in the database look like:
{"order": 123, "type": "shipping", "amount": 0.39, "notes": "8.50%"}
{"order": 456, "type": "small-order", "amount": 2.50, "notes": "Automatically Added"}
I'm not wild about the “Automatically Added” (do we have fees that are
manually assessed?), but having room for an optional note of some kind
makes sense.
Shipping and small-order fees are the only ones I know of, but we can
easily extend this to new fees by adding entries to orderFeeType.
The explicit orderFee.id, orderFee.order, and use of an array for
order.fees instead of an object are setting us up for an `/order-fee`
endpoint if we decide to move fee management into the API
(e.g. letting internal UIs POST fees to orders, or DELETE fees from …
=> public.json: Add order.fees

public.json
This brings updateTrip in line with the trip model (the only
difference is updateTrip not requiring an ID).  We need delivery-start
when creating a trip, because stop-time estimates are based on that
delivery-start date, and there's not much point in scheduling a trip
that cannot make stop-time estimates.  And there's work in progress to
move stop-creation from verification time up to trip-creation time, in
which case "there's not much point" becomes "the POST will crash".
=> public.json: Require updateTrip.delivery-start

public.json
The value from 64bc196a (public.json: Add order.fees, 2015-10-02, #40)
was just copy/pasted from telephone.type.description.
=> public.json: Fix orderFee.type.description

public.json
Consider the following example:
* Route r1 has trips t1 and t2 before cutoff.
* Route r1 has drops d1 and d2 associated with it through route-stops
(r1,d1) and (r1,d2).
So possible stops are (t1,d1), (t1,d2), (t2,d1), and (t2,d2).  The old
workflow created those stops at verification time, so pre-verification
delivery estimates were based on the route-stops (r1,d1) and (r2,d2).
If logistics wanted to shift the delivery estimate for (t1,d1) before
that stop was created at t1-verification time, they'd update (r1,d1),
which would also shift (t2,d1).
[In the 2015-04-27 meeting][1], David wanted to keep that per-route
timing without allowing per-trip timing changes (e.g. shifting (t1,d1)
without shifting (t2,d1) before either trip was verified).
[By 2015-12-15][2], the requested business logic …
=> public.json: Create stops at trip-creation time

public.json
The size, unit, and packs are what is being audited and those are
attributes of the packaged-product, therefore the audited attribute
should be on the packaged-product, not the product.
=> move audited attribute from productAudit to packagedProductAudit

public.json
This slipped through 2fd234af (move audited attribute from
productAudit to packagedProductAudit, 2016-02-02, #67).
=> public.json: Shift 'audited' requirement from productAudit to packagedProductAudit

public.json
This snuck in with 01861207 (public.json: Add person.price-level and a
multi-level price object, 2015-09-16, #29), but a person can only
belong to one price-level at a time.  And our currently-implemented
API uses a single entry:
$ curl -su wking:... https://api.azurestandard.com/person | jq .
{
...
"price-level": "retail",
...
}
=> public.json: person.price-level is not an array

public.json
Add a way to retrieve permissions for your authenticated user
(`/person`) or someone else (`/person/{id}`).  This currently has very
coarse permissions for whether the person is staff or a superuser
(with all permissions), so we can do things like only exposing the
internal-website UI to staff (internal-website#48).  Moving forward,
we can fill this in with entries like `create-address`,
`update-address`, and `delete-address` for folks who can CrUD
`/addresses`, etc.  That level of granularity will take time, but this
setting will let us add per-endpoint permissions and migrate per-UI
checks [as we see fit][2].
There's some discussion in internal-website#48 about where to put this
information, with `/session` and a new `/permissions` being floated.  I've
gone with `/person` here, because: …
=> public.json: Add person.permissions

public.json
Fix a typo from e4fc603 (public.json: Add person.permissions,
2016-02-08, #71).
=> public.json: Fix 'permissions' -> 'permission' for definition key

public.json
For azurestandard/website#143, we'll need to calculate order-line weight and volume, without creating an order-line via the API.
=> public.json: Add volume and weight to packaged-product

public.json
The [user-facing website specs][1] have, in section 9.7.1 (the
drop-coordinator's "Current Drop" page), a table of previous
deliveries to that drop.  Columns showing data in that table are:
* "Route" for trip.route.
* "Departure" for the trip.shipped added in this commit.
* "Delivered" for the stop.time associated with the given trip and
drop.
* "Orders" for the number of orders associated with the given trip and
drop.
[1]: https://docs.google.com/document/d/1dwayyitTQT5ma-UhFfkC16i6aVrJ2ArV-HnUdWyst10/edit#
=> public.json: Add trip.shipped

public.json
Stops don't have cutoff times, and the current API implementation
orders them by target time.
=> public.json: Fix 'cutoff' -> 'target' time ordering for /stops

public.json
=> Fix 'persion' typo and broken JSON from #71

public.json
Reading through azurestandard/beehive#1330 reminded me that we didn't
have a way to reset passwords with the new API-based website, so I'm
adding one here.
POSTing a known email address to /password/reset will cause a message
to be sent to that address.  The email will contain a link with a
reset token, and that token can be POSTed to /password/confirm to set
a new password.  This base-url / token approach is just like the one
used for registration, and we support both POST and GET confirmations
for the same reasons (see 182d6c9, public.json: Add 'GET
/registration/confirm?token=...', 2015-09-03, #19).
/password/confirm returns the person whose password was reset, so the
UI can display their name, etc. in a successful-reset page.
=> public.json: Add 'POST /password/reset' and 'POST /password/confirm'

public.json
This is a more limited version of `/packaged-products?tag=…`, since
[implementing that for more remote models has been troublesome][1].
The idea with this filter is that we can [preserve favorites
associated with discontinued products in the database but easily avoid
those favorites in the client][2].  Then if/when the product is picked
up again, the client using `active=true` would automatically pick it
back up.
I expect most clients will want to set `active=true`, but the
only-active functionality is behind a query parameter to keep the
stock `/favorites` from becoming too magical (with entries appearing
and disappearing based on associated-packaging status).  Having a
query parameter also makes it easy for clients who care to find and
delete inactive favorites on their own.
[1]: …
=> public.json: Add /favorites?active={true|false}

public.json
Similar to address.preference, but this is set by Azure on categories
shared by all users, while address.preference is set by customers on
their own addresses.  I've tried to reflect that shift by changing the
attribute name from 'preference' to 'featured'.
An example use-case would be to fetch the top N child categories of a
given parent, without having to care about the details behind the
definition of "top".
=> public.json: Add category.featured

public.json
Colin [raised a question about handling products whose packaging has incompatible units][1], because it's hard to compare prices between packaging like that.  The choices are:
a. Allow incompatible units in the database, and handle inconsistencies when rendering that packaging in the API implementation.
b. Refuse incompatible units at data-entry time, so there are no audited inconsistencies in the database.
Either way, the rendering will have to handle products which do not have completely audited packaging, but (b) makes it easier for auditors to find and fix such occurrences while also protecting packaging-managers from typos.  And packaging-managers are the most likely to be able to resolve the inconsistency, so showing them the error shortens that bugfix cycle a lot ;).
On Fri, Mar …
=> public.json: Add 'GET /audit/product/{id}' and .clear-audited

public.json
In order to facilitate displaying as-low-as pricing on the front end,
include the calculated price per unit. This will allow the front end to
select which packaging has the lowest price per unit and keeps the
separate pricing levels.
resolves #90
=> add dollars-per-unit and unit fields to _price

public.json
So employees can mark orders they want paid for out of their next
paycheck.
There is no newPayrollDeduction, because these methods are created via
the Beehive UI and not via the API (yet).  And employees will not be
creating these on their own behalf (while most customers create
credit-card methods by uploading their credit-card information on
their own behalf).
There's no special information associated with this method, but we'll
keep a person ID for symmetry with the credit-card type.
=> public.json: Add a payroll-deduction payment method

public.json
JavaScript makes it easy to set headers on an `XMLHttpRequest` or
similar, but it's hard to set headers like that in an `<a href="…">`
link (there is an advisory [`type` attribute][1], but it's just a hint,
not a suggestion for the `Accept` header that the agent should use when
following that link).  You may be able to work around this with some
draft [File API][3] [blob manipulation][2] or by [reading the data into
memory and building a][4] [data URI][5], but those are both more trouble
than getting a PDF or CSV order representation should require.
This commit adds a new `accept` query parameter, so clients that have
trouble setting an `Accept` header have an alternative channel for
supplying that information.
It also documents (with a [per-operation `produces`][6]) the supported
MIME …
=> public.json: Add ?accept=<mime> to GET /order/{id}

public.json
Code is a nullable field and not all packaged-products have a code.
This prevents that packaged-product from being audited. Changing the
identifier to id allows all packaged-products to be audited.
see azurestandard/internal-website#79
=> packagedProductAudit change code to id

public.json
And adjust limit phrasing for Count.  Details in the commit messages.
The two changes aren't really related, but I noticed the phrasing
issue while fixing /favorites.  If either seems controversial, I'm
happy to split into two PRs.
=> public.json: Add pagination (limit, start, Count) to /favorites

public.json
Currently only supports `packaged-product`.
=> Update /favorites endpoint to support inlined properties.

public.json
You should be able to do:
/favorites?inline=packaged-product,packaged-product.product
although that's going to be the same as:
/favorites?inline=packaged-product.product
The CSV-ness will be more important if the inline-able objects split.
For example, if we wanted to make packagedProduct.stock optional,
requests could look like:
/favorites?inline=packaged-product.product,packaged-product.stock
The backend [already assumes the value is CSV][1].
[1]: https://github.com/azurestandard/beehive/pull/1715/commits/ae54f89994246e557438a44405b2cc4c0303f7b8#diff-afa3ac3d703b3410c74ee6769662e13dR203
=> public.json: /favorites?inline=... is a CSV array, not a single string

public.json
This was missed in 2b0dc9ac (public.json: Adjust products to key on
ID, and not packaging code, 2015-02-18) and the subsequent e87fa01f
(public.json: Fix 'package-product' -> 'packaged-product' typo,
2015-02-19).
=> public.json: Fix 'product' -> 'packaged-product' in orderLine required

public.json
This allows us to return historical payment methods (e.g. so customers
can see which method they used for a past payment), while still
allowing customers to distinguish between methods that can and cannot
be used for new payments.
The permissions around toggling .active will be complicated.  For
example, a customer should be allowed to change creditCard.active from
true to false if they want to disable a particular card.  In that
case, they should also be able to immediately change .active back to
true.  However, they should not be able to re-activate cards that have
expired, or re-activate payroll-deductions if they are no longer an
employee.  The backend may implement whatever restrictions it feels
are appropriate in this respect, and clients should be prepared to
handle assorted 400s …
=> public.json: Add .active to payment methods

public.json
This reverts #45 and takes another pass at the purchase/pickup
modeling now that I understand it better.  See [here][1] for an
overview of our current database representation.  The API I'm
proposing makes the following adjustments to those database models:
* Squashes `BackhaulPickup` and `Purchase` into the purchase API (like
`Order` and `OrderShipment` are squashed into `Order`).
`BackhaulPickup` is one-to-one with `Purchase`, so this squash can
be lossless.
* Exposes `VendorContact` through the pickup API.  I expect there will
be the same sort of confusion here that we got from the `Product` →
packaged-product and `PieceMeta` → product renaming, but I think
‘pickup’ is a clear echo of ‘drop’ and ‘vendor-contact’ doesn't
strike me as a physical location that could be shared by several …
=> Logistics APIs for purchases and pickups

public.json
adds the type of payment to the payment model to allow for
displaying the payment type as described in azurestandard/website#209
=> add type to payment model

public.json
[Typo][1] from 4a700af (add type to payment model, 2016-05-06, #112).
[1]: https://circleci.com/gh/azurestandard/api-spec/270
=> public.json: Remove trailing comma in payment.type

public.json
This came in with 8a05c761 (add drop membership endpoints and
definitions, 2016-01-27, #66), and we just missed the required value
when rerolling to [drop the dropMembership.name property][1].
[1]: https://github.com/azurestandard/api-spec/pull/66#issuecomment-178158238
=> public.json: Remove vestigial 'name' from dropMembership.required

public.json
Instead of just net-10 and net-30.  These slugs have already been
exposed by the API.
=> Use net-10-days and net-30-days slugs for generic payment methods.

public.json
Allow provisional memberships (“Please let me in”) for folks joining
semi-open or closed drops.  Drop coordinators and/or customer-service
can hit:
GET /drop-memberships?pending=true&...
to see who has asked to join drops (or, with `&drop={drop.id}`, who has
asked to join their drop).  They can fetch all memberships, pending or
accepted, by not specifying the `pending` parameter.  And they can
fetch only accepted memberships with `pending=false`.
Drop coordinators and/or customer-service can also accept requests by
PUTing with pending false.  And they can reject requests by DELETE'ing
the membership ([we aren't currently doing anything special for
rejections on the backend][1]).
I haven't setup a default value in `updateDropMembership` because the
reasonable choice depends on the drop …
=> public.json: Add dropMembership.pending

public.json
The previous spec wording was unclear, but the current site includes
breakdown ancestors, so we want to mimic that here [1].  You can
almost figure out the ancestor-included values from the direct values
(e.g. if we set 0 stock for the 6 x 14 and 14 oz packaging in the new
doc example), but the API doesn't clarify what can be broken down into
what.
[1]: https://github.com/azurestandard/beehive/issues/1780
=> public.json: Include breakdown ancestors in packagedProduct.stock

public.json
The old website exposes this information with text like:
> You can continue modifying this order until May 16, 2016 at 6 p.m.
This change exposes parcel-carrier cutoff information to customers, so they can figure out when orders will cutoff (last call for (un)placing orders on that trip).
This could also allow customers to place orders on future parcel-carrier trips, although the Angular UI isn't planning on supporting that, and the backend might 400 such attempts.
I'm leaving order.drop unset for parcel-carrier orders, because it doesn't add any useful information (order.address already has the delivery location).
Also change “UPS” to the more generic “parcel-carrier”.
=> public.json: Allow order.trip for parcel-carrier orders

public.json
The GET versions were added in 182d6c9 (public.json: Add 'GET
/registration/confirm?token=...', 2015-09-03, #19) and a94f2e29
(public.json: Add 'POST /password/reset' and 'POST /password/confirm',
2015-11-13, #52) to give folks something they could paste into their
browser.  We don't need that though, because clients can set base-url
to generate links to a non-API page, and have that non-API page POST
to the API ([Slack discussion][1]).  Users are unlikely to GET the API
directly, because the returned JSON isn't very user-friendly.
[1]: https://azurestandard.slack.com/archives/general/p1458760386001170
=> public.json: Drop GET for /registration/confirm and /password/confirm

public.json
Since 81687725 (add dollars-per-unit and unit fields to _price,
2016-04-06, #92) added fields using "unit" to mean "pounds", "quarts",
and such, the old "per-unit" phrasing in the per-pound docs might be
confusing.  Pick new wording to clarify that if per-pound is false, it
means that 'dollars' is per-product (e.g. $6.50 means "the three-pack
of coconut water is $15", not "one ounce of coconut water is $6.50").
This phrasing (and some other price docs) blur the distinction between
"products" (unsized in most of the API) and "packaging" (sized in most
of the API), but I've stuck with "product" here for consistency with
the other price docs.  I'd also be ok with "per-packaging", although
that might also get confusing for things like three-packs.
=> public.json: Reword "per-unit" to "per-product" in the per-pound docs

public.json
These landed in 61bba865 (public.json: Add a POST-based /login
endpoint, 2015-05-20) and 7ac3aa3f (public.json: Add a /logout
endpoint, 2015-05-27).  The /login case was clearly (from the commit
message) an accidental copy/paste error, and I expect the latter was
too.  The GET -> POST change respects [RFC 7231's safe methods][1].
[1]: http://tools.ietf.org/html/rfc7231#section-4.2.1
=> public.json: Fix 'get' -> 'post' for /login and /logout

public.json
David McAtee proposed this change, which brings the phrasing more in
line with purchase.status and fits better with a shopping model that
could include multiple pre-cutoff orders.  It went over well at the
2016-06-03 developer meeting and the 2016-06-06 software meeting.
See azurestandard/website#425.
=> public.json: Rename 'cart' -> 'open' for order status

public.json
And add `?save=false` support.  This lets folks check the side effects
of an order-save (e.g. maybe they adjusted the shipment from a drop to
parcel-carrier, and want to know if we'll still ship all of their
ordered products via parcel-carrier).
PUTting an order can also change fees and such, but those aren't listed in
`.changes` because clients can compare the resulting `.order` with a previous
retrieval.  Comparing order lines with that approach would require more
work up-front to collect the original data, and more post-PUT work to see
if any lines had been removed or changed.
We currently only record line-removals in `.changes`.  But with the
coming price overhaul, shipping costs are probably going to be
per-line (Slack 2016-03-15), in which case we'll probably grow a …
=> public.json: Adjust PUT /order/{id} to return a changedOrder model

public.json
On Thu, Apr 28, 2016 at 02:24:35PM -0700, Tom Peters [wrote][1]:
> Rebecca reported that there was talk of UPC/Barcodes being
> searchable.
This makes a lot of sense to me, especially for wholesalers and such
who want to scan a barcode to order more of a product they're running
low on.  The new field and semantics [follow][2] [schema.org][3].
Internally, we allow a product to have several barcodes, and I'm fine
supporting all GTIN-13-compatible barcodes for search.  But for
compatibility with schema.org we should just be returning the primary
barcode here.
[1]: https://github.com/azurestandard/website/issues/304
[2]: https://schema.org/Product
[3]: https://schema.org/gtin13
=> public.json: Add packagedProduct.gtin13 and ?gtin13=... filters

public.json
This requires backend tooling for azurestandard/internal-website#51
(as discussed with @tompetersjr and @jeffstrickler on 2016-02-10),
which allows for simpler client-side code.  Details in the commit
messages.
=> public.json: Fill in POST/PUT/DELETE for stop and support propagation

public.json
To allow for non-size distinctions between packaging without having to
split them into separate product families.  The vinegar example is for
CO463, but this change will also be useful for variable-weight
packaging such as MT159 (6 x 6-10 lb turkey).
=> public.json: Add updatePackagedProductAudit.size

public.json
Because, while you need an email address in order to receive the reset
token, you may not remember which address you've given Azure.  I'm
keeping 'email' as the property name here (both for backward compat
and because it is the most closely tied to the token delivery), but
the new description borrows from login's 'username' property to allow
the other common identifiers.
With this approach, the backend has to figure out whether the uploaded
identifier is an email, username, or person ID, but that logic has to
happen somewhere, and the API is smaller if we push it to the backend.
If we wanted the type-detection to happen in the frontend, we'd have
to use oneOf or similar JSON Schema stuff.  I like it when the API is
explicit, because it allows for a simpler backend and UIs that
distinguish …
=> public.json: Allow username and person IDs in password resets

public.json
This gives customer-service and short-drop members a way to find their
post-cutoff and pre-confirmation short stops for stoppage-time
shopping (see [here][1]).  It also gives folks with existing orders a
way to tell if they will be able to make post-cutoff edits to placed
orders or not, without having to push changes and watch for errors.
More details on the individual changes in the commit messages.
CC @MercenaryJosh, @davidmcatee-azure.
[1]: https://github.com/azurestandard/website/commit/5566db1cd84fffce7420bead6d52571697be3c62#commitcomment-17516147
=> Add /trips?confirmed=(true|false) and /stops?short-drop=(true=false)

public.json
This allows the backend to use more expensive fee-estimation logic (e.g. hitting parcel-carrier APIs) without bogging down order manipulations.  We initially [expected order-manipulation hitting fee recalculation to be rare][1], but it turns out to be [unacceptably slow][2], and [we don't need the fee information most of the time][3] (or it's ok if the fee update shows up asynchronously a second or two so after the change that triggered it).
[1]: https://github.com/azurestandard/website/issues/186#issuecomment-213072160
[2]: https://github.com/azurestandard/website/issues/552#issue-165217215
[3]: https://github.com/azurestandard/website/issues/552#issuecomment-232406614
=> public.json: Split order.fees into its own endpoint

public.json
On Wed, Jul 06, 2016 at 02:33:14PM -0700, Joe Isitt [wrote][1]:
> New system doesn't allow customers to add order notes like they did
> in the old site.  I presume it was planned this way, however a CSR
> pointed out today that these fields are used for error repairs and
> other things.
The backend will implement this by exposing
OrderShipment.special_instructions.
[1]: https://github.com/azurestandard/website/issues/507
=> public.json: Add order.notes

public.json
There was already a `/payment-method/{id}` key for GET (Circle also had some indent complaints in #136).
This method deactivates the method (instead of deleting it), because we keep old method information around for displaying old invoices.
We will also allow customers to associate inactive (but unexpired) credit cards with orders to support the “‘Save card for future purchases’ false” workflow.
=> public.json: JSON fixups for payment-method DELETE

public.json
David Stelzer pointed out that the customer experience is nicer if we can tell them why their stop is late, instead of just that it is late.
=> public.json: Add trip.notes

public.json
On Wed, Jul 27, 2016 at 09:02:00AM -0700, Tom Peters [wrote][1]:
> Note that the label on this field should now be `Warehouse Packing
> Instructions` according to this email from Debbie.
>
> > I know the software team is working on adding special
> > instructions.  As we make this addition to the site, please know
> > that people sometimes use those to communicate with Azure
> > management or customer service. This requires the warehouse to
> > send us the message.
> >
> > Could you change the TEXT for that box to "Warehouse Packing
> > Instructions", which is really all we want that box utilized for -
> > to communicate with the warehouse during picking and packaging.
This commit updates the description to match, since we didn't have such a specific workflow description in f648ee30 …
=> public.json: Make order.notes description more specific

public.json
required by azurestandard/website#710
Only include the last-four if the payment method was 'Credit Card'.
=> include the last four digits of the credit card used to make a payment

public.json
So we can return should-not-buy warnings like:
> {product.code} is likely to expire before it gets to {drop.name}
> ({drop.id}) via {route.code}.
This will help with cart rendering and quick-add.  More discussion
[here][1] and [here][2].
[1]: https://github.com/azurestandard/website/issues/754#issuecomment-238982722
[2]: https://github.com/azurestandard/website/issues/718#issuecomment-237717173
=> public.json: Add orderLine.warnings

public.json
Like 1accb50 (public.json: Add .active to payment methods, 2016-04-27,
#106), this gives a way to remember previous memberships.  Inactive
members can no longer place orders on drop, but drop coordinators
still have some access to inactive member information (e.g. their
name) so they can render old orders (azurestandard/website#726).  Also
related to azurestandard/website#365.
Require `updateDropMembership.active` to make the PUT endpoint more
explicit and less PATCH-like.  But don't require
`updateDropMembership.pending` to match the implementation landed in
azurestandard/beehive#1846.
More details in the commit messages.
=> public.json: Add dropMembership.active

public.json
This gives us a convenient place to store errors (e.g. per-address bounce
reports) and lets us access multiple addresses per person
(although the backend currently caps that at three emails per person).
Multiple emails per person allows you to include others (e.g. family
members) in cutoff-notifcations and the like, although only the primary
address (with the highest preference) is used for password-reset, login,
and the like.
Also fill in the address API to catch up with the current
implementation, because I'm using the address API to template the new
email API.
Related issues: azurestandard/beehive#510, azurestandard/beehive#1806, azurestandard/website#624.
=> public.json: Split out email addresses into their own endpoints

public.json
This is needed for the internal-website category app to link to
products on the new website. see azurestandard/internal-website#145
=> include product id in packagedProductProduct

public.json
Return resend tokens from POST and PUT, and add an `/emails/resend` endpoint to receive those tokens.  This allows the following workflow:
1. User submits new / updated email.
2. Frontend shows user:
> You've submitted your update and will receive a confirmation
>  email shortly.  You can click here to resend the email.
POSTing the resend token to `/emails/resend` if the user clicks.
3. User gets the confirmation email and visits the confirmation URL.
4. Frontend gets the confirmation token from the URL, and submits
token to `/emails/confirm`.  On success, frontend shows the user:
> Email update confirmed.
and whatever else it wants to say.
The frontend can skip step 2 and show the user something else if they don't want to support resends.
The confirmation email is not sent and the resend …
=> public.json: Add /emails/resend and adjust email requirements

public.json
We're not sure what the business logic is for multiple errorless emails.  Our backend (Beehive) has (for a while now) sent all customer email to all addresses that looked remotely valid.  With azurestandard/beehive#2105, Beehive keeps track of per-address errors and sends mail to all addresses that don't have errors.  The frontend, however, has traditionally only shown drop coordinators a single email address per customer.  It's not clear to Casey, David McAtee, or me whether the different frontend handling is intentional or an oversight from the transition that shifted the backend from one to three email addresses per customer.  We'll talk about this more on Monday, but for
now, this commit gives the frontend an easy way to preserve its current functionality despite the new email API. …
=> public.json: Add GET ...?inline=email to /people and /person/{id}

public.json
On Fri, Sep 02, 2016 at 09:08:12AM -0700, Tom Peters wrote [1]:
> > Just so you know... We are prepping up to offer pallets, totes and
> > barrels on our website.  Especially totes and barrels will need a
> > dock or forklift or liftgate.  So when something over 110# is
> > ordered, a custom report that is run every day after cutoff will
> > show the customers that are able to receive these heavy items. If
> > not CC will need to call the customer and find out if they can.
> > This is pretty manual, but will get us started.  Eventually we
> > could warn customers when they place it in their cart, if they are
> > not approved for heavy delivery.  And or warn CC someone ordered a
> > heavy item.
> >
> > Soon I would like to add characteristics to our routes, like max
> > trailer weight and …
=> public.json: Add dropMembership.heavy

public.json
This change would allow clients to treat a successful /registration/confirm response as a successful login of the user that was activated. Login would only occur if activation was successful, so it would only work once per token as activation does.
This would allow for a more streamlined registration flow, as the front end will be able to immediately engage the user with links to add a drop, fill out profile information, etc., without them having to sign in first.
If possible, I would like to get this in as a precursor to azurestandard/website#653.
=> Registration confirmation also performs login.

public.json
From [here][1]:
> Azure is a proudly independent company that supports other small,
> independent businesses. The Azure Indie Partner Program is designed
> to support companies that share our passion for a free and
> independent supply chain.
>
> These are forward-thinking, independently owned, health-conscious
> companies that deserve your business. They’re not just concerned
> with short-term profits. They’re passionate about making a
> difference in the world over the long run.
API change for azurestandard/beehive#2233.
[1]: https://www.azurestandard.com/healthy-living/indie-partner-program/
=> public.json: Add vendor.indie

public.json
Drop coordinators are used to seeing these counts broken down by climate, with [separate counts for greenhouse, frozen, and dry/chilled][1].
Also unifies the storage types so `drop.storage` and `product.storage` (was `product.storage-climate`) share the same enum.  Before we land this, we should check and see if drops can opt in/out of storing greenhouse products.
[1]: https://github.com/azurestandard/beehive/blob/226ec6956970fa83c220c4ee4b05d6e35cf27294/apps/shipping/templates/shipping/pdfs/cover_sheets.html#L83-L103
=> public.json: Per-storage entries for order.cases-shipped

public.json
As a read-only property, although we still haven't split this into
stop and updateStop.  This lets us figure out what the offset will be
if the frontend bumps a stop time forward by a day (or whatever) since
you might trip in or out of daylight savings time.
=> public.json: Add stop.timezone

public.json
These will be used for managing BarTender print configurations in the
internal website.  There is a special endpoint for testing a print
configuration.  Also, minimal definitions of warehouses and printers
(PrinterOptions) are exposed in order to create print configurations.
=> Add definitions and endpoints for BarTender integration.

public.json
The new site is live and we've dropped the old site, so there's no more need for this setting.
=> public.json: Drop person.opt-in-beta-site

public.json
Also remove the empty-security override, make resend tokens optional, and typo-fix "resent" -> "re-sent".
The old ID-less version matched /emails/confirm.  Confirmation shouldn't rely on the email ID for the reasons described in #149.  However, the frontend triggering resends should be able to use both tokens and the usual basic/cookie credentials to trigger a resend.  By shifting /emails/resend to /email/{id}/resent, we give frontend a way to pass the ID without passing the token (which encodes the ID, among other things).  Passing the token still works; folks who pass the token will now need to track both the token and the email ID, but both are part of the updatedEmail payload so that shouldn't be a problem.
Fixes #168.
=> public.json: Move /emails/resend to /email/{id}/resend

public.json
Since folks listing child categories should have an easy way to filter out the inactive ones.
Spun off from azurestandard/internal-website#166.
=> public.json: Add /categories?active=(true|false)

public.json
For updateEmailUserPassword requests.
=> public.json: Only require base-url when the email address changes

public.json
Expose the slug that the backend uses to produce canonical links, giving
consumers a way to produce links with a better guarantee of consistency.
=> Add slug to brand, product, and category

public.json
The ip2location endpoint must detect the user's ip address as well as
return the location data.
=> remove ipaddress from /ip2location

public.json
Reduce the number of places where we define similar-but-not-identical models for the same thing.  Use `?inline=…` to allow callers to push joins to the backend, avoiding multiple API calls for client-side joins.
CC @MercenaryJosh, @tompetersjr, since this touches the API which just landed in #175.
CC @davidmcatee-azure, since I'm not sure how much trouble updating the current frontend's address consumers to follow the address.country-name → address.country change will be.
=> public.json: Use country in address and address in ip2location

public.json
When the user provides an email address, check for existing accounts which use that email address.
* If an inactive account using the email address is found, send an inactive-member email pointing the user at customer service.  Return a resend token, but do not authenticate the user.
* If an active account using the email address is found, send an active-member email with an authenticating token.  Return a resend token, but do not authenticate the user until they provide the auth token.
* If no account using that email address is found, create a new account and immediately authenticate the user.  If they provided an email address or SMS number, potentially send a welcome-aboard notification.  Any email address will remain unconfirmed until the user completes a confirmation cycle.
This …
=> public.json: Authenticate successful registrations immediately

public.json
And `confirmation-base-url`, since we now have two different tokens that we might be mailing the registrant.
I've gone with “channel” instead of “email” in the description, because we might to authenticate additional channels besides email (e.g. SMS) in the future.
=> public.json: Change registration base-url to authentication-base-url

public.json
The general `sort` query parameter means additionally sort fields can be
added in the future.  Since the distance needs to be calculated from a
lat + lon input, a special format is used here.
Fixes #179.
=> Allow sorting drops by distance.

public.json
Our backend has several ways to store notes associated with a given user:
1. In an append-only array of internal notes with no UI for editing existing notes (via the Django comments app).
2. In an internal, editable text field usually used for billing notes.
3. In an editable text field for default shipping instructions, which the customer and internal users can see.
This commit exposes (2).  Our immediate use-case is for recording promotion codes and similar at registration time so we can create credits for signing bonuses and the like.
Also two API fixups to match our current implementation, since some changes were made without a leading API-spec PR.
=> person: Add .internal-notes

public.json
Details in the commit-messages (which also includes a drive-by fix for
product's required array).
This covers [this request](https://github.com/azurestandard/beehive/pull/1715#issuecomment-215227195) while setting up the product and
packaged-product endpoints to be a bit more structured and performant.
=> public.json: Inlines for product.packaging and packagedProduct.product

public.json
The registration-resend needs both authentication and confirmation base URLs to catch up with 33c0652 (#183).
=> public.json: Split resendConfirmationEmail from resendRegistrationEmail

public.json
The previous language wasn't clear if this information was for Azure only, or whether members should also be able to read it.
On Tue, Jan 17, 2017 at 04:50:27PM -0800, Nick Gall [wrote][1]:
> > The front end does indeed hide the notes on open drops for everyone.  Are we sure we only want to show open drop notes to the primary contact, coordinator, and customer service? @nickgall's OP wasn't clear on that point.  If so, then this is only a simple front end change.  If not, back end changes will be required to broaden access to notes.
>
> We will want to show these notes publicly; for both semi-open and open drops.  We'll have an employee review all the notes to make sure they are appropriate via a (yet to be created?) report.
I'm guessing on the closed drops, but if the open and semi-open …
=> public.json: Document audience for drop.notes

public.json
So users can calculate shipping fees will be without changing the order and hitting `/order-fees`.  The backend [currently hard-codes this at 8.5%][1] and allows the setting to be toggled at the [route-stop][2] level [with a route-level mask][3], so I have not added the new property to `updateStop`.
[1]: https://github.com/azurestandard/beehive/blob/3f30eac07f26dfa62785f4e6999d5562adafbba0/apps/drops/models.py#L983-L984
[2]: https://github.com/azurestandard/beehive/blob/3f30eac07f26dfa62785f4e6999d5562adafbba0/apps/drops/models.py#L839
[3]: https://github.com/azurestandard/beehive/blob/3f30eac07f26dfa62785f4e6999d5562adafbba0/apps/routes/models.py#L206-L210
=> public.json: Add stop.shipping-fee

public.json
Correct a typo from d2a35b36 (`public.json`: Add `GET /route-stops` and `/route-stop/{id}` endpoints, 2015-05-07).
=> public.json: Fix 'estimated-time' -> 'delivery-offset' for routeStop required

public.json
On Thu, Jun 08, 2017 at 10:04:21AM -0700, Casey M. Bessette [wrote][1]:
> Had a hangout meeting with Stephen and Rebecca today about this.  Some pieces such as https://beehive.azurestandard.com/piece/20264 have Servings per Container added to the Nutritional Facts, e.g.,
>
> ```
> Serving Size: 1/4 cup (30 g)
> Servings Per Container: About 378 (25 lb. size)
> Servings Per Container: About 151 (10 lb. size)
> Servings Per Container: About 75 (5 lb. size)
> ...
> ```
>
> In this case you see it's per piece (not piece meta) data even though it's currently stored on piece meta.
On Thu, Jun 08, 2017 at 12:53:12PM -0700, Tom Peters [wrote][2]:
> Note that by [removing "Servings per Container" from `product.nutrition-facts`] the `Servings per Container` will be removed from the websites …
=> public.json: Add packaging.servings-per-container

public.json
Catching up with azurestandard/beehive#1801.
On Tue, Apr 05, 2016 at 04:53:20PM -0700, Stephen Hainline [wrote][1]:
> Currently, if a customer orders a 3/pack and we only have two, the picker can pick 2 and short the rest without resistance from the picking interface.  The result of this is that the customer is getting free product.  There is currently a setting somewhere, probably in products to Allow Partial Sale.  However, this does not seem to be working in practical reality and the customers are not getting charged per Carmen.  They are requesting some kind of resolution to this.
[1]: https://github.com/azurestandard/beehive/issues/1687
=> public.json: Convert int to float for orderLine.quantity-shipped

public.json
Opening this PR to give us a place to discuss the format for the new endpoint we're going to create to handle retrieving parcel carrier shipping estimates for orders. 
The commit I've included will end up looking something this
```
[
{
"order": 13414,
"service-name": "UPS Next Day Air",
"shipping-days": 1,
"cost": 55.00,
"guaranteed": false,
},
{
"order": 13414,
"service-name": "UPS 2-Day Express",
"shipping-days": 2,
"cost": 25.00,
"guaranteed": true,
},
]
```
=> Add order parcel carrier shipping endpoint and definition

public.json
I'm not sure if this is entirely legal Swagger, but it gets the idea across.
@davidmcatee-azure [wants this because it's more convenient than paging][1].  The [brands API is cheap][2], so I'm not worried about the load of unlimited `/brands` requests.
I want to keep the default limit lower than the cap to make it less likely that users accidentally submit expensive requests.  If you want a high-limit or unlimited response, you need to ask for it explicitly.
[Potential APIs][3] for explicitly unlimited responses:
a. Pick an absurdly high number (`?limit=999999999`).
b. Use a sentinal value (`?limit=null`, `?limit=none`, `?limit=unlimited`, `?limit=-1`, …).
I don't have a personal preference, but @davidmcatee-azure [liked `?limit=none`][4], so that's what I'm using here.
Part of …
=> public.json: Add limit=none support for /brands

public.json
Adds the following fields to the /person endpoint
- affiliate-code
- is-allowed-to-be-affiliate
- accepted-affiliate-terms
Add the following fields to the /registration endpoint
- pap-visitor
- referring-affiliate
- pap-banner
Supporting [Beehive #2986](https://github.com/azurestandard/beehive/pull/2986)
=> Fields for Post Affiliate Pro (PAP)

public.json
So that clients can walk back to the root category with a single API request.
Previous discussion in azurestandard/beehive#2785 and azurestandard/beehive#2868.
=> public.json: Add ?inline=ancestors for /categories and /category/{id}

public.json
In today's meeting, David Stelzer said that prompting users to confirm their email with warnings like “we won't be able to send cutoff reminders until you confirm your email address” will be insufficient motivation.  Instead, we should assume addresses work as entered, and only record errors for bounces and such.  That means we don't need a
confirmation URL in the registration email, since there hasn't been time for anything to go wrong yet.
This is somewhat unwinding #183, although I've left the more-specific `authentication-base-url` (instead of changing it back to `base-url`) to protect against other sorts of URLs we might want to include later.
=> public.json: Remove email confirmation

public.json
Reopening #155, since GitHub closed that one after an accidental merge (which we've since rolled back).
=> Add packs and unit to packagedProduct definition

public.json
The website is [currently][1] setting a [`<title>` element][2] based on [hard-coded values][3] like this.  The values landed in the website via azurestandard/website@a801e764 citing azurestandard/website#654 and landing titles like:
> Organic Chicken & Animal Feed in Bulk - Organic Farming & Garden Supplies
[provided by Lee Ladyga][5].  That's a pretty long title; too long for our [sidebar listing sub-categories][6].  But the name in the sidebar is easier to read if it's not as compact as the short name, which we want to use for breadcrumbs, URL slugs, and such (azurestandard/website#1738).  So we have three different size needs:
* A longish form for `<title>` (`seo-name`).
* A medium form for the sidebar and other low-context locations (`name`).
* A short form for breadcrumbs, URL slugs, …
=> public.json: Add category.seo-name and category.description

public.json
This should have happened in #122, which added an entry to `orderLine`'s `required`, but only added the name property to `updateOrderLine`.
=> public.json: Document orderLine.name

public.json
And make the `cost` and `climate` properties optional since they will
not be provided for the UPS Freight and Azure Wholesale Team services.
Related to azurestandard/website#1673.
=> Add orderParcelCarrierEstimate.message.

public.json
And rename `errorModel` to `error.  Everything under definitions is a model; there's no need to call that out in the name.
I was cleaning this up as part of azurestandard/website#1520.  It turns out we probably won't need error.slug for that workflow, but the cleanups here are probably still useful.
=> public.json: Add descriptions for error.code and error.message

public.json
If a customer has carried a sufficiently large balance for a sufficiently long time (as determined by the backend), we want to at least warn users instead of letting them silently checkout (and continue to grow their balance).  We have a few classes of customers for this situation:
* Some customers have fairly serious issues, and they should be encouraged to contact customer service to resolve the issue.  Until then, we will block attempts to place orders.
* Some customers have fairly standard issues, and they should be encouraged to settle their balance directly (e.g. via the “Make a Payment” button [here][1]).  They can also call customer service to sort things out that way.  Until their balance is resolved, we will block attempts to place orders.
* Some customers have special …
=> public.json: Add person.order-place-issue

public.json
Like we already do for email.address, etc.
=> public.json: Add the 'email' format for affiliate-username

public.json
And factor `updateCategory` out from `category`.  Details in the commit messages.
This addresses azurestandard/beehive#3387 and documents the changes I just floated [here][1].
[1]: https://github.com/azurestandard/beehive/pull/3443#issuecomment-356504553
=> public.json: Add 'depth' inline to category endpoints

public.json
And don't require user-password for users without a usable password.  This makes it easier for customers who register without a password to initialize their password later, because their existing auth token (or a cookie obtained by logging in with that token) is now sufficient information for `PUT`ing a new password.  Previously, they'd have to go through the password-reset email cycle, [which was tedious][1].
This makes those accounts slightly more exposed to [ambient authority attacks][2] and cookie/token leakage.  But our API considers cookie/token possession sufficient for most operations already.  Users who want the stricter `user-password` protections for the extra-sensitive password and email updates are free to set a password, either at registration time or later, without us …
=> public.json: Add person.password-usable

public.json
[As][2] [requested][1] by @davidcross so the frontend can slot in tailored home page content.  Personally, I'd be happier [if the place times only included orders which remained in the database][3], but that's not my call.
We also discussed using cookies for this information, but decided on person properties so customer service can see the same home page as a customer when they are acting on the customer's behalf (`?superuser-for=...`).
[1]: https://github.com/azurestandard/website/issues/2161
[2]: https://github.com/azurestandard/beehive/issues/3735
[3]: https://github.com/azurestandard/beehive/issues/3735#issuecomment-385823868
=> public.json: Add RFM, first-order-placed, etc. to person

public.json
This allows us to show things like "lifetime rewards", so folks can see the total impact of the rewards program on their account.  You can retrieve the previous balance value with `credit-total - debit-total`.
We don't want to do this for `accountEntry`, because we don't expect to break that down for folks (e.g. no "lifetime dollars sent to Azure" UI).
=> public.json: Split reward.balance into total-credit and total-debit

public.json
This is something like `person.price-level`, allowing users to calculate the rewards they'll earn for a particular product before they add an order-line.  Once they've added an order line, they can use `orderLine.rewards`.
In our previous modeling from 6074db6 (#230), we assumed a single standard rate across all customers.  In recent discussion, we have decided to relax that, and allow for per-customer rewards rates.  The new property allows customers (and customer service) to determine that rate.
We'll want follow-up work to adjust the price changes from 6074db6 to account for this change, now that `_price.rewards` is no longer a thing.  But I'm not clear enough on what those changes will look like yet, so we're punting them to follow-up work.
I've gone with integer percentages based on: …
=> public.json: Add a per-customer rewards rate

public.json
We have per-customer rewards rates since 2e149cf6 (#232), so a per-packaging `reward` value no longer makes sense.  This commit replaces the logic from 6074db6b (#230).  Bonus rewards can now be calculated by comparing `_price.rewards-rate` with `person.rewards-rate`, so we no longer need `*-standard` properties.
`_price.rewards` and `.rewards-standard` used to be required, for the reasons discussed in 6074db6b.  The new `_price.rewards-rate` is not required, and having `_price.rewards-rate` unset means the rewards rate for that packaging floats with `person.rewards-rate`.
Now that we're using the percentage rewards-rate (which scales with price), we can drop the `rewards-per-unit*` properties.  We'd mentioned that we might remove those in 6074db6b, and now we're removing them.
Also …
=> public.json: Adjust _price for per-customer rewards rates

public.json
This allows the front-end to filter for "affiliate-referral" credits.
=> Add "reason" filter to "account-entries" endpoint.

public.json
Note that this is the first of our new "computed" concept (distinct from "inline"). To recap the difference (from notes taken via discussion that resulting in the concept): 
Use `inline` for nested properties.
Use `computed` for computed properties (returned JSON nested inside a `computed` property)
Also note that I've used camel case here, as I understood we wanted to do all future API-related development using it (and will at some point convert existing hyphenation to it).
=> Add computed total properties to order endpoint

public.json
And update rewards-related descriptions to account for our change in
logic.
=> Add product.maxRewardsRate.

public.yaml
To be consistant with other endpoints the new route fields
added in PR #261 should be required on the route model
- hub
- driverName
- driverPhone
- notes
=> Make Route Fields Required

public.yaml
Updates the spec for  https://github.com/azurestandard/beehive/pull/4414/commits/f2f91396286255fd95b77ef97891fa988826c70d.
Assuming we want to try and keep the spec accurate with the production API we should hold off on merging this until that (above mentioned PR) is deployed.
=> Add status property to trip

README.md, public.yaml
Details: 
- Adds a "Style Guide" section to the readme.
- Makes formatting changes to match those specified in the style guide.
- Removes the block start syntax (`>-`) from `summary` properties (as `summary` should always be a simple string)
- Replaces the block start syntax (`>-`) on the `description` properties with `|-` (see https://yaml-multiline.info/ for differences). This is to support new lines in the description values, which are utilized by documentation tools. Also, when editing in Stoplight.io, this is the block start syntax that gets used, so another motivation for this is to prevent merge conflicts when editing between different tools.
=> Improve formatting consistency

spec.json
This is for the latest code in PR: https://github.com/azurestandard/beehive/pull/5188 
@igregson I could not remember how to update this spec in the UI of https://azurestandard.stoplight.io/docs/api-spec/public.yaml so I just modified the code manually in the spec.json to add the field that is now getting returned in the `updateOrder` endpoint.
=> Add parcelCarrierShipByDate field to the spec for updateOrder endpoint

package-lock.json, package.json
The effectively gets us on the latest version of Redoc (at least via the latest version of the cli that's published to NPM (which is 0.10.2, while 0.10.4 is the latest in GitHub)).
Redoc's changelog: https://github.com/Redocly/redoc/blob/master/CHANGELOG.md
=> Upgrade Redoc cli to v0.10.x

spec.json
For https://github.com/azurestandard/beehive/issues/5444.
In discussion with Tom and Thomas we were thinking to name the property `finalizedState`. While creating this PR, however, it became clear to me that a more descriptive name is `finalizedDeliveryState` (further reasoning: The date-time property is named `finalizedDelivery`, and this property essentially describes the state of that property, so "extending" its name seems to make good sense (i.e. `finalizedDelivery + [state]`)). Of course feel free to share any reasons we may not want to go with `finalizedDeliveryState`.
=> Add finalized delivery state param to stop

spec.json
Details:
- Adds missing response properties to the `packaged-products` endpoints.
- Adds missing query parameters to the `packaged-products` endpoints (and fixes the descriptions on some existing ones that didn't mention their relation to the `inline` query parameter).
- Adds "audit" to the descriptions of the `audit/product*` endpoints to help differentiate them with the non-audit product endpoints.
- Changes tags on product-related endpoints for improved grouping in the ReDoc docs (so that they are now grouped more logically with their endpoints). Previously these were not organized clearly, with most of the endpoints showing under "product" but others under "image" and "packaged-product-tag". We now have them organized by: 
- product
- packaged-product
- packaged-product-image
- …
=> Make fixes/improvements to packaged-products endpoints

spec.json
While working on another change, I noticed the `"style": "form"` property on certain parameters that we pass in the querystring in the form of CSV. I wasn't quite sure what it meant so I looked it up in the [OpenAPI 3](https://swagger.io/specification/) spec:
Notice that the default value of the `explode` field is `true` when `style` is `"form"`. However, since we treat these parameters as CSV, we want `explode` to be `false`. An example further down the page confirms this:
This PR adds `"explode": false` to all query parameters that we treat as CSV.
=> Add `"explode": false` to CSV parameters

spec.json
This is needed for the frontend to use some of the promo-code endpoints.
For context, see: 
- https://github.com/azurestandard/beehive/pull/5884#issuecomment-974141741
- https://github.com/azurestandard/beehive/pull/5884#issuecomment-974258070
=> Add id to promoCode response object

spec.json
Updates the spec for changes made here: https://github.com/azurestandard/beehive/pull/5884#issuecomment-1039707758
=> Add `replace` query param to promo code POST

README.md, package.json
Resolves #340
Also updates our "engines" entry in package.json (for accuracy and consistency since CF Pages uses these versions and these are the same versions we use in our other repos).
Notes:
- URL for Pages' project in the CF panel: https://dash.cloudflare.com/6003ffc5444305b2caff9dc3886e6ae8/pages/view/api-spec
=> Migrate from Netlify to CF Pages
