azurestandard/api-spec

public.json

1. GET /person/preferences/packaged-product-tags
2. POST /person/preferences/packaged-product-tags
3. DELETE /person/preferences/packaged-product-tag/{tag}
Fixes #11.

Add methods to manage a person's filter preferences.

---

public.json

This is for https://github.com/azurestandard/beehive/issues/1186.

Add allow-social-media property to person definitions.

---

public.json

Let me know if there's anything that doesn't look right. The fields were requested for UI work but there was no real spec so the changes could be slightly off.
code change branch: https://github.com/azurestandard/beehive/pull/1231

Add new fields to route reponse schema

---

circle.yml

I think this is the right Circle CI syntax, but we should wait and see
how well it works before merging ;).

circle.yml: Use jq to test for JSON syntax errors

---

public.json

adds the changes to the packaged-products api response introduced in #29673dc.

add fields to packaged-product that are required for the categories app.

---

public.json

Adds fields to the category model and a query parameter to /packaged-products in order to add the new features and requirements to the Category model and in the categories app.

Primary Category

---

public.json

For https://github.com/azurestandard/beehive/issues/1483.

Add directions to product definition.

---

public.json

Spec changes for https://github.com/azurestandard/beehive/pull/1482

Add remaining drop settings & preferences.

---

public.json

The variable weight addition should have been included in #68.

public.json: Add variable weight to packaged-product

---

public.json

Missing a closing brace } along with the comma ,.

Fix Syntax Error

---

public.json

This will hold preferences.fee_amount_and_structure.

Add dropFees.notes to definition.

---

public.json

For the new category of customers that manage will-call drops.
The API side of azurestandard/beehive#1560.
There's also a drive-by typo fix.

public.json: Add 'member' pricing

---

circle.yml
public.json

I'm not going to remember to check this without continuous integration
;).

circle.yml: Ensure formatting matches jq's recommendation

---

public.json

Adds parameters to the /audit/products endpoint required to search for products and to filter products by given packaged-product codes.
These parameters are needed to fulfill the requirements in azurestandard/internal-website#81

/audit/products search and packaged-product

---

public.json

Details in the commit messages.
Fixes #111.

public.json: Add additional generic payment methods (cash-on-delivery, etc.)

---

public.json

Related API changeset: https://github.com/azurestandard/beehive/pull/1836

Add countries and country-regions endpoints and definitions.

---

public.json

Also document POST, PUT, and DELETE for order-lines.  Details in the
commit messages.  Related to azurestandard/beehive#1489 and azurestandard/beehive#1786.

public.json: Add orderLine.name (and make packaged-product optional)

---

public.json

add country of origin to product

---

public.json

Add payment-method delete

---

public.json

see azurestandard/internal-website#128

add created attribute to drop-membership definition

---

public.json

Add total-cases to order definition.

---

public.json

see azurestandard/beehive#2179

add storage-climate to the product definition

---

public.json

ref https://github.com/azurestandard/beehive/issues/2133

Add packs and unit to packagedProduct definition

---

public.json

Adds endpoint and definition to support integration of ip2address.
see azurestandard/website#946
and azurestandard/beehive#2263

add endpoint and definition for ip lookup

---

public.json

seems like this may have been a merge error?

fix missing parameters attribute line

---

public.json

I found this branch locally, and we may need some of it for @davidmcatee-azure's getting-started reroll.

Optional registration passwords and catalog-request cleanup

---

public.json

For azurestandard/beehive#2495.

Add sort parameter to drop-memberships.

---

public.json

For https://github.com/azurestandard/beehive/pull/2691.

Add product.short-description to definition.

---

public.json

The internal pricing UI wants to use this for autocompletion.  We could update the pricing UI to use Algolia, but implementing this filter on our backend is pretty easy, and it will let the pricing UI work even without external connectivity.

public.json: Add ?name=... to /brands

---

public.json

Backend work in Beehive [#2593](https://github.com/azurestandard/beehive/pull/2593)

API Spec for the Company Directory

---

public.json

For https://github.com/azurestandard/beehive/issues/2948 and https://github.com/azurestandard/beehive/issues/3061.

Add report endpoints and definitions.

---

public.json

For https://github.com/azurestandard/beehive/issues/2943.

Add order.perishable-shipping-warning-accepted.

---

public.json

And remove orderParcelCarrierEstimate.message which was from a previous
iteration of the feature specification.

Add orderParcelCarrierEstimate.contact-for-quote.

---

public.json

For use with https://github.com/azurestandard/beehive/pull/3323.

Add person.affiliate-username.

---

public.json

The API side of azurestandard/beehive#3774.

public.json: API for the rewards program

---

public.json

Add affiliate referrals

---

public.json

For https://github.com/azurestandard/beehive/issues/4061.

Add inline "gratitude-total" prop to dropMembership definition

---

public.json

For https://github.com/azurestandard/beehive/issues/4077.

Add inline "is-drop-coordinator" prop to person definition

---

public.json

For https://github.com/azurestandard/beehive/issues/4119.

Add orderFrequencySegment endpoint and computed property to person

---

public.json

For response changes requested to the `order-frequency-segment` endpoint via https://github.com/azurestandard/website/issues/2582#issuecomment-448876545.

Update order-frequency-segment endpoint

---

public.json

As requested via https://github.com/azurestandard/api-spec/pull/244#issuecomment-445012359.

Update computed properties on the order endpoint

---

public.json

For https://github.com/azurestandard/beehive/issues/4248.

Add dropMembershipId to order inline response

---

public.json

For https://github.com/azurestandard/website/issues/2640.

Changes for parcel out of stock handling

---

public.yaml

Adding the following fields:
- hub
- driverName
- driverPhone
- notes
In support of https://github.com/azurestandard/beehive/pull/4313

Add new route fields

---

public.yaml

For API changes decided in the context of https://github.com/azurestandard/internal-website/pull/233.

Update some stop properties

---

public.yaml

Needed for Website support (https://github.com/azurestandard/website/pull/2847) of Beehive https://github.com/azurestandard/beehive/pull/4412.

Add abandonedCart property to personNotifications

---

public.yaml

Resulting clarification from work/review/discussion around https://github.com/azurestandard/beehive/issues/4451.

Clarify stop persist option

---

public.yaml

Found these inside of the Stoplight interface (https://azurestandard.stoplight.io/studio/api-spec/edit).

Fix validation errors

---

spec.json

Add actualDeliveryBackdated to stop endpoints

---

spec.json

Update route definition

---

spec.json

Update stop endpoints and response

---

spec.json

Add support for a truckload concept to the API.
Fixes: #289

API Truckload Support

---

spec.json

Follow-up to https://github.com/azurestandard/api-spec/pull/293#discussion_r508726648.

Add note about query param array format

---

spec.json

Resolves #284 
Also fixes two misspellings (unrelated to the issue this resolves).

Add mail/route and mail/trip endpoints

---

spec.json

Add drops/actions/convert-route endpoint

---

spec.json

Related Beehive issue: https://github.com/azurestandard/beehive/issues/5065

Add timezone to drop and pickup response objects

---

spec.json

Document customerHasPlacedOrderOnDrop query param

---

package.json

Specify Node and NPM versions

---

spec.json

Use in favor of https://github.com/azurestandard/api-spec/pull/308

updated stops spec with truckload obj

---

spec.json

Implemented by https://github.com/azurestandard/beehive/pull/5330.

Add ordered-packaged-products endpoint

---

spec.json

Get Product Property Fixes

---

spec.json

This adds customer and internal notes to the API Spec on Order Lines.

Add order lines to API Spec

---

spec.json

Implemented in https://github.com/azurestandard/beehive/pull/6054.

Add `id` parameter to `/products`

---

spec.json

Motivation/backstory: https://github.com/azurestandard/website/pull/3459#issuecomment-956739289

Add inline truckDriver to stop endpoints

---

spec.json

This new order status prop is being added via https://github.com/azurestandard/beehive/pull/7594

Add new order status prop `delivered-to-drop`
